spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productsapi
    username: productsapi
    password: productsapi

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  cloud:
    openfeign:
      client:
        config:
          products-api:
            read-timeout: 3000
            connect-timeout: 5000


fake-api:
  url: https://fakestoreapi.com

  cloud:
    loadbalancer:
      ribbon:
        enable: true